version: 1
formatters:
  brief:
    format: '%(levelname)s - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
loggers:
  gensim:
    level: ERROR
    handlers: [console]
  nonce2vec:
    level: WARNING
    handlers: [console]
  nonce2vec.models:
    level: WARNING
    handlers: [console]
root:
  level: INFO
  handlers: [console]
